# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"


# Plugins
plugins=(
	zsh-autosuggestions
	fast-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# Alias
alias install='sudo apt install -y'
alias uninstall='sudo apt remove'
alias update='sudo apt update -y && sudo apt upgrade -y && flatpak update -y && snap refresh -y'
alias clean='sudo apt autoclean && sudo apt autoremove'
alias fix='sudo apt install -f'
alias moo='apt moo'
alias tux='cowsay -f tux'
alias cls='clear'
alias cd..='cd ..'

alias python='python3'
alias py=python

alias term='gedit ~/.zshrc'

alias env_activate='source ./env/bin/activate'
alias venv_activate='source ./venv/bin/activate'

alias cp_pwd="pwd && pwd | xclip -selection clipboard"

alias cube="$CUBE_PATH/STM32CubeMX"
alias remake="cd .. && rm -rf build && mkdir build && cd build && cmake .."
alias old_remake="make clean_all clean_cube clean cube prepare; make -j"


for file in $HOME/scripts/*.py; do

	name=$(basename "$file" .py)
	alias "$name"="python3 \"$file\""

done

# Functions

function compile_c(){
    # Compile and run C files
	name=$(ls *.c | head -n 1 | cut -d'.' -f1)
	mkdir -p out
	gcc "${name}.c" -o "out/${name}.o" -lm
	./out/${name}.o
}

# Export

export PATH="/home/eduardo-barreto/Apps/gcc-arm-none-eabi-10.3-2021.10/bin/:$PATH"
export PATH="/home/eduardo-barreto/STMicroelectronics/STM32Cube/STM32CubeProgrammer/bin:$PATH"
export CUBE_PATH="/home/eduardo-barreto/STM32CubeMX"

export VISUAL="gedit"

# Other settings

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
